/* Generated by MyraPad at 02.02.2020 20:44:10 */
using Microsoft.Xna.Framework;
using monoGameCP;
namespace ScreenManager
{
	public partial class MapSizePropertiesWindow
	{
		public MapSizePropertiesWindow(GraphicsDeviceManager graphics)
		{
			BuildUI(graphics);
		}
	}
}