/* Generated by MyraPad at 02.02.2020 20:53:27 */
using Myra.Assets;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using System;
using monoGameCP;
#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace ScreenManager
{
	 public delegate void gridMapDimensionsChangeHandler(int width,int height,int tileSize);

  
    partial class MapSizePropertiesWindow: Window
	{
		public event gridMapDimensionsChangeHandler changedGridMapToUse;

		private void BuildUI(GraphicsDeviceManager graphics)
		{
			var label1 = new Label();
			label1.Text = "Tile Size: ";

			tileSize = new TextBox();
			tileSize.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			tileSize.MinWidth = 100;
			tileSize.MaxWidth = 100;
			tileSize.Width = 200;
			tileSize.Id = "tileSize";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(tileSize);

			var label2 = new Label();
			label2.Text = "Map X:";

			mapWidthX = new TextBox();
			mapWidthX.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			mapWidthX.Id = "mapWidthX";

			var label3 = new Label();
			label3.Text = "Map Y:";
			label3.Left = 100;
			label3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			mapHeigthY = new TextBox();
			mapHeigthY.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			mapHeigthY.Left = 100;
			mapHeigthY.Id = "mapHeigthY";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Widgets.Add(label2);
			horizontalStackPanel2.Widgets.Add(mapWidthX);
			horizontalStackPanel2.Widgets.Add(label3);
			horizontalStackPanel2.Widgets.Add(mapHeigthY);

			changeGridSave = new TextButton();
			changeGridSave.Text = "Change Grid Size";
			changeGridSave.Left = 360;
			changeGridSave.Id = "changeGridSave";
			changeGridSave.Click += (s, a) =>
			{
		
            var width=Int32.Parse(mapWidthX.Text);//x oige
            var height=Int32.Parse(mapHeigthY.Text);//y
            var tileSizeVa=Int32.Parse(tileSize.Text);//tile
            changedGridMapToUse((int)width,(int)height,(int)tileSizeVa);
          
		
			};

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Widgets.Add(changeGridSave);

			var label4 = new Label();
			label4.Text = "Window width:";

			windowWidthX = new TextBox();
			windowWidthX.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			windowWidthX.Id = "windowWidthX";

			var label5 = new Label();
			label5.Text = "Window Height:";
			label5.Left = 40;
			label5.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			windowHeigthY = new TextBox();
			windowHeigthY.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			windowHeigthY.Left = 40;
			windowHeigthY.Id = "windowHeigthY";

			var horizontalStackPanel4 = new HorizontalStackPanel();
			horizontalStackPanel4.Widgets.Add(label4);
			horizontalStackPanel4.Widgets.Add(windowWidthX);
			horizontalStackPanel4.Widgets.Add(label5);
			horizontalStackPanel4.Widgets.Add(windowHeigthY);

			changeWindowSave = new TextButton();
			changeWindowSave.Text = "Change Window Size";
			changeWindowSave.Left = 360;
			changeWindowSave.Id = "changeWindowSave";
			changeWindowSave.Click += (s, a) =>
			{
		
				var width=Int32.Parse(windowWidthX.Text);//x oige
				var height=Int32.Parse(windowHeigthY.Text);//y
				
				graphics.PreferredBackBufferHeight = (int)height;
				graphics.PreferredBackBufferWidth = (int)width;
				graphics.ApplyChanges();
			// drawGridSystem((int)width,(int)height,(int)tileSize);
		
			};
			var horizontalStackPanel5 = new HorizontalStackPanel();
			horizontalStackPanel5.Widgets.Add(changeWindowSave);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel2);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel3);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel4);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel5);

			
			Title = "";
			Left = 223;
			Top = 7;
			MinWidth = 500;
			MaxWidth = 600;
			MinHeight = 500;
			MaxHeight = 600;
			Id = "mapPropertiesWindow";
			Content = verticalStackPanel1;
		}

		
		public TextBox tileSize;
		public TextBox mapWidthX;
		public TextBox mapHeigthY;
		public TextButton changeGridSave;
		public TextBox windowWidthX;
		public TextBox windowHeigthY;
		public TextButton changeWindowSave;
	}
}