/* Generated by MyraPad at 26.01.2020 22:50:18 */
using monoGameCP;
namespace UIMenusAndControls
{
	public partial class TilePropertiesWindow
	{
		public TilePropertiesWindow(TileObject tile)
		{
			BuildUI(tile);
		}
	}
}